config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'admin/sessions#new'
  get '/logout' => 'admin/sessions#destroy'

  namespace :admin do
    resources :posts
    resources :sessions, only: [:new, :create, :destroy]
    resources :moderators, only: [:index, :edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :visitor
  has_many :notifications, as: :notifiable
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :visitor
end

app/models/moderator.rb
class Moderator < ApplicationRecord
  has_secure_password

  has_many :posts

  validates :fullname, presence: true
  validates :username, presence: true, format: {with: /@/, message: 'is not valid'}
  validates :password, presence: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notifiable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :tags, through: :post_tags
  belongs_to :moderator
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :posts, through: :post_tags
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  has_many :notifiactions, as: :notifiable
  has_many :comments
  has_many :messages
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  layout 'admin'
  before_action :authorize

  def current_moderator
    @moderator ||= Moderator.find(session[:current_moderator_id]) if session[:current_moderator_id]
  end

  def authorize
    unless current_moderator
      redirect_to '/login', alert: 'Please login to view admin pages.'
    end
  end
end

app/controllers/admin/moderators_controller.rb
class Admin::ModeratorsController < Admin::ApplicationController
  def index
    @moderators = Moderator.all
  end

  def edit
    @moderator = Moderator.find(params[:id])
  end

  def update
    @moderator = Moderator.find(params[:id])

    if @moderator.update(moderator_params)
      flash[:notice] = "Moderator was successfully created."
      redirect_to admin_moderators_url
    else
      flash[:alert] = "There was a problem updating moderator."
      render 'edit'
    end
  end

  private

  def moderator_params
    params.require(:moderator).permit(:id, :fullname, :username, :password)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def show
  end

  def destroy
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::ApplicationController
  before_action :authorize, except: [:new, :create]

  def new
  end

  def create
    @moderator = Moderator.find_by(username: params[:username]).try(:authenticate, params[:password])
    if @moderator
      session[:current_moderator_id] = @moderator.id
      redirect_to admin_moderators_url, notice: "You have  successfully signed in"
    else
      flash[:alert] = "There was a problem with your username or password"
      render :new
    end
  end

  def destroy
    session[:current_moderator_id] = nil
    redirect_to '/login', notice: 'You have successfully logged out'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/moderators/edit.html.erb
<h1>Edit Moderators</h1>

<% if @moderator.errors.any? %>
  <div id="validation_errors">
    <h2><%= pluralize(@moderator.errors.count, "error") %> prohibited this moderator from being saved:</h2>

    <ul>
    <% @moderator.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [:admin, @moderator] do |f| %>
  <p>
    <%= f.label :fullname %>
    <%= f.text_field :fullname %>
  </p>

  <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/admin/moderators/index.html.erb
<h1>Moderators</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>fullname</th>
      <th>username</th>
      <th>created</th>
      <th>actions</th>
    </tr>
  </thead>
  <tbody>
    <% @moderators.each do |moderator| %>
    <tr>
      <td><%= moderator.fullname %></td>
      <td><%= moderator.username %></td>
      <td><%= time_ago_in_words(moderator.created_at) %></td>
      <td><%= link_to 'Edit', edit_admin_moderator_path(moderator) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/posts/edit.html.erb
<h1>Admin::Posts#edit</h1>
<p>Find me in app/views/admin/posts/edit.html.erb</p>

app/views/admin/posts/index.html.erb
<h1>Posts</h1>

app/views/admin/posts/new.html.erb
<h1>Admin::Posts#new</h1>
<p>Find me in app/views/admin/posts/new.html.erb</p>

app/views/admin/posts/show.html.erb
<h1>Admin::Posts#show</h1>
<p>Find me in app/views/admin/posts/show.html.erb</p>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert"><%= flash[:alert] %></div>
    <% end %>

    <%= link_to 'Log out', logout_path %>

    <p>
      <%= link_to 'Posts', admin_posts_path %>
      <%= link_to 'Moderator', admin_moderators_path %>
    </p>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert"><%= flash[:alert] %></div>
    <% end %>
    <%= yield %>
  </body>
</html>